### ISSUE TITLE
USER STORY: Home page template and Header

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#11]
As a **user** I can **land on an intuitive, welcoming and simple site** so that **I can understand the purpose easily**

**Acceptance criteria**
- Landing page visible to user 
- Header content visible

**Tasks**
- [x] Create Home template and set up URL
- [x] Add Boostrap and custom CSS
- [x] Add Header content to base.html
