### ISSUE TITLE
USER STORY: Product Details

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#19]
As a **user** I can **access the details of each item** so that **I can read and inform before purchase**

**Acceptance criteria**
- Products detailed page displayed to users on all screen sizes
- Page is in style with the site

**Tasks**
- [x] Create products detail template
- [x] Create view and wire up URL
- [x] Bootsrap and CSS

**Comment by noemichis** [comment]
Created item details page and added Bootstrap.
