### ISSUE TITLE
TASK: Start app and early deploy to Heroku

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#3]
**Task description**
Create a basic Django project that can be deployed.

- [x] Create Project
- [x] Create env.py -> .gitignore
- [x] Hide variables
- [x] Wire up Heroku and the Database
- [x] Create Procfile
- [x] Early deploy to Heroku

**Comment by noemichis** [comment]
Early deployment successfull both locally and on Heroku.
