### ISSUE TITLE
USER STORY: Add/Update/Remove

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#32]
As a **user** I can **add/update/remove items from my bag** in order to **have a better shopping experience**

**Acceptance criteria**
- Items can be added/updated/removed from bag

**Tasks**
- [x] Set up add/update/remove functionality
- [x] Update templates and wire up
- [x] Bootsrap and CSS

**Comment by noemichis** [comment]
Functionality to add/remove and update item quantity complete, style complete. Will have a look on medium up screens for cart buttons later.
