### ISSUE TITLE
USER STORY: Admin CRUD form for site interface

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#46]
As a **user** I can **add/update/delete items on the website interface** so that **I can manage them without logging into the admin panel**

**Acceptance criteria**
- Admin CRUD for product management

**Tasks**
- [x] Add product form
- [x] Create product managament view, template and wire up URL
- [x] Add/update/delete functionality

**Comment by noemichis** [comment]
Admin CRUD tested on interface, no issues noticed so far. Item and image upload work as expected, update as well.
