### ISSUE TITLE
TASK: Resolve authentication issues

### ISSUE THREAD

**Issue by noemichis** [noemichis/devil-on-pans#84]
**Task description**
Authentication is not working as expected

- [x] Email confirmation on registration
- [x] Role base authentication
- [x] Login/registration only for anonymus users

**Comment by noemichis** [comment]
email address verification sent successfully.
Login/register only if anonymus.
Product management page/edit/delete product visible only for admin
